import { Injectable } from '@angular/core';
import { IAlertLogItem } from "../models/alert-log-item";
@Injectable({
  providedIn: 'root'
})
export class AlertLogService {

  EXAMPLE_DATA: IAlertLogItem[] = [
    {
      "alertLogId": 99158,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-23 15:40:15",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99157,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-23 15:15:06",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99156,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-23 15:14:49",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99155,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-23 13:28:24",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99154,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-23 13:27:18",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99153,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-23 13:25:26",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99152,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-23 13:24:27",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99151,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-23 12:56:52",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99150,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-23 12:51:12",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99149,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-23 11:02:04",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99148,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-23 10:07:23",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99147,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-23 09:36:50",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99146,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-23 08:47:08",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99145,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-22 23:58:54",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99144,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-22 23:56:46",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99143,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-22 16:10:29",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99142,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-22 16:02:24",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99141,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-22 15:23:06",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99140,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-22 15:22:28",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99139,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-22 14:55:25",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99138,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-22 14:45:47",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99137,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-22 14:37:35",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99136,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-22 14:22:24",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99135,
      "logText": " نام کلاف معتبر نمیباشد.",
      "logDate": "2020-06-22 14:20:02",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99134,
      "logText": " نام کلاف معتبر نمیباشد.",
      "logDate": "2020-06-22 13:51:20",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99133,
      "logText": " نام کلاف معتبر نمیباشد.",
      "logDate": "2020-06-22 13:49:58",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99132,
      "logText": " نام کلاف معتبر نمیباشد.",
      "logDate": "2020-06-22 13:49:09",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99131,
      "logText": " نام کلاف معتبر نمیباشد.",
      "logDate": "2020-06-22 13:48:07",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99130,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-22 13:47:47",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99129,
      "logText": " نام کلاف معتبر نمیباشد.",
      "logDate": "2020-06-22 13:46:34",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99125,
      "logText": " نام کلاف معتبر نمیباشد.",
      "logDate": "2020-06-22 13:29:31",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99123,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-22 13:23:03",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99122,
      "logText": " خطا رخ داده است.",
      "logDate": "2020-06-22 13:22:07",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99121,
      "logText": " خطا رخ داده است.",
      "logDate": "2020-06-22 13:21:07",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99120,
      "logText": " خطا رخ داده است.",
      "logDate": "2020-06-22 13:20:36",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99119,
      "logText": " خطا رخ داده است.",
      "logDate": "2020-06-22 13:19:14",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99118,
      "logText": " کلاف با شماره  یافت نشد",
      "logDate": "2020-06-22 13:10:56",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99117,
      "logText": " کلاف با شماره  یافت نشد",
      "logDate": "2020-06-22 13:10:36",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99116,
      "logText": " کلاف با شماره  یافت نشد",
      "logDate": "2020-06-22 13:10:27",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99115,
      "logText": " کلاف با شماره 556565 یافت نشد",
      "logDate": "2020-06-22 13:09:29",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99114,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-22 13:05:44",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99113,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-22 10:32:13",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99112,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-22 10:28:32",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99111,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-22 10:28:25",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99110,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-22 09:45:04",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99109,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 17:13:36",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99108,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 17:13:36",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99107,
      "logText": " عملیات ویرایش با موفقیت انجام شد.",
      "logDate": "2020-06-21 17:13:36",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99106,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 17:13:36",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99105,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 17:13:31",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99104,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 17:13:31",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99103,
      "logText": " عملیات ویرایش با موفقیت انجام شد.",
      "logDate": "2020-06-21 17:13:23",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99102,
      "logText": " خطا رخ داده است.",
      "logDate": "2020-06-21 17:13:04",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99101,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 17:12:49",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99100,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 17:12:49",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99099,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 17:12:49",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99098,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 17:12:49",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99097,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 17:07:45",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99096,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 17:07:36",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99095,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 17:04:16",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99094,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 16:49:47",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99093,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 16:47:15",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99092,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 16:44:14",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99091,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 16:42:54",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99090,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 16:41:04",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99089,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 16:40:49",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99088,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 16:38:26",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99087,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 16:35:44",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99086,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 16:35:12",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99085,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 16:25:07",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99084,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 16:25:07",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99083,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 15:24:08",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99082,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 15:24:08",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99081,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 14:53:06",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99080,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 14:49:32",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99079,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 14:46:20",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99078,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 13:54:01",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99077,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 13:10:49",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99076,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 11:38:01",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99075,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 11:34:44",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99074,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 11:29:04",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99073,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 11:28:10",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99072,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 11:20:59",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99071,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 11:19:44",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99070,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 11:16:10",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99069,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 11:12:50",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99068,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 11:12:50",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99067,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 11:12:15",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99066,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 11:12:15",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99065,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 11:12:15",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99064,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 11:12:15",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99063,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 11:12:15",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99062,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 11:12:15",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99061,
      "logText": " عملیات ویرایش با موفقیت انجام شد.",
      "logDate": "2020-06-21 11:12:15",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99060,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 11:12:12",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99059,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 11:12:11",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99058,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 11:11:55",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99057,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 11:11:55",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99056,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 11:11:35",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    },
    {
      "alertLogId": 99055,
      "logText": " عملیات افزودن با موفقیت انجام شد.",
      "logDate": "2020-06-21 11:11:35",
      "prm1Value": null,
      "prm2Value": null,
      "prm3Value": null,
      "alertId": 1000,
      "title": "GENERAL",
      "sound": true,
      "popup": false,
      "type": 1
    }
  ]
  ALERT_LIST = [
    {
      "alertId": 1000,
      "title": "GENERAL",
      "template": " ",
      "prm1Title": null,
      "prm2Title": null,
      "prm3Title": null,
      "isSound": true,
      "isPopup": false,
      "isActvie": true,
      "isPublic": true,
      "alertTypeFk": 1,
      "alertTypeFkNavigation": null,
      "alertLog": [],
      "connectUgAlert": []
    },
    {
      "alertId": 2007,
      "title": "1071-1",
      "template": "درخواست نام برای کلاف با شماره @1 ارسال گردید",
      "prm1Title": null,
      "prm2Title": null,
      "prm3Title": null,
      "isSound": false,
      "isPopup": false,
      "isActvie": true,
      "isPublic": false,
      "alertTypeFk": 1,
      "alertTypeFkNavigation": null,
      "alertLog": [],
      "connectUgAlert": []
    },
    {
      "alertId": 2008,
      "title": "1071-2",
      "template": "کلاف با شماره @1 یافت نشد",
      "prm1Title": null,
      "prm2Title": null,
      "prm3Title": null,
      "isSound": false,
      "isPopup": false,
      "isActvie": true,
      "isPublic": false,
      "alertTypeFk": 1,
      "alertTypeFkNavigation": null,
      "alertLog": [],
      "connectUgAlert": []
    }
  ]

  constructor() { }

  async readAlerts() {
    return await this.ALERT_LIST
  }

  async getAlertLogList() {
    return await this.EXAMPLE_DATA
  }
}
